# train.py

import torch
import torch.utils.data as data
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingLR
from src.trc import TRC


# -----------------------------------------------------------------------
# Hyperparameters — directly from paper Section IV and V-A
# -----------------------------------------------------------------------

CONFIG = {
    # Problem dimensions
    "d_x":      2,
    "d_u":      1,
    "T":        100,

    # Architecture — Section III-A
    "d_z":      256,
    "d_h":      512,
    "L":        3,
    "num_heads": 8,
    "K":        3,
    "n":        4,
    "u_min":    -2.0,
    "u_max":     2.0,

    # Training — Section IV
    "epochs":       50,
    "batch_size":   32,
    "lr":           1e-3,
    "grad_clip":    1.0,
    "lam":          0.1,    # process supervision weight lambda

    # Cost matrices — Section V-A Eq. (19)
    "Q":  torch.tensor([[10., 0.], [0., 5.]]),
    "R":  0.5,
    "Qf": 20.0 * torch.tensor([[10., 0.], [0., 5.]]),

    # Dataset paths — generated by your SQP solver
    "train_path": "van_der_pol_train.pt",
    "test_path":  "van_der_pol_test.pt",

    # Checkpoint
    "checkpoint_path": "trc_checkpoint.pt",
}


# -----------------------------------------------------------------------
# Dataset
# -----------------------------------------------------------------------

class VanDerPolDataset(data.Dataset):
    """
    Wraps the .pt file saved by your SQP dataset generator.
    Each sample is (x0, x_target, u_star).
    """
    def __init__(self, path):
        dataset = torch.load(path)
        self.x0       = dataset["x0"]        # (N, 2)
        self.x_target = dataset["x_target"]  # (N, 2)
        self.u_star   = dataset["u_star"]    # (N, T, 1)

    def __len__(self):
        return len(self.x0)

    def __getitem__(self, idx):
        return self.x0[idx], self.x_target[idx], self.u_star[idx]


# -----------------------------------------------------------------------
# Validation
# -----------------------------------------------------------------------

def validate(model, loader, device, config):
    """
    Run one pass over the validation set.
    Returns mean loss, mean improvement, and mean achieved cost.
    These are the two metrics shown in Figure 2 of the paper.
    """
    model.eval()
    Q  = config["Q"].to(device)
    Qf = config["Qf"].to(device)
    R  = config["R"]

    total_loss        = 0.0
    total_improvement = 0.0
    total_cost        = 0.0
    n_batches         = 0

    with torch.no_grad():
        for x0, x_target, u_star in loader:
            x0       = x0.to(device)
            x_target = x_target.to(device)
            u_star   = u_star.to(device)

            all_u = model(
                x0, x_target,
                dynamics_fn=model.van_der_pol.simulate,
                return_all_iters=True,
            )

            _, info = model.loss(all_u, u_star, x0, Q, R, Qf, lam=config["lam"])

            total_loss        += info["loss"]
            total_improvement += info["improvement"]
            total_cost        += info["JK_mean"]
            n_batches         += 1

    return (
        total_loss        / n_batches,
        total_improvement / n_batches,
        total_cost        / n_batches,
    )


# -----------------------------------------------------------------------
# Training loop
# -----------------------------------------------------------------------

def train():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Training on {device}")

    # ---- Cost matrices on device ----
    Q  = CONFIG["Q"].to(device)
    Qf = CONFIG["Qf"].to(device)
    R  = CONFIG["R"]

    # ---- Model ----
    model = TRC(
        d_x      = CONFIG["d_x"],
        d_u      = CONFIG["d_u"],
        T        = CONFIG["T"],
        K        = CONFIG["K"],
        n        = CONFIG["n"],
        d_z      = CONFIG["d_z"],
        d_h      = CONFIG["d_h"],
        L        = CONFIG["L"],
        num_heads= CONFIG["num_heads"],
        u_min    = CONFIG["u_min"],
        u_max    = CONFIG["u_max"],
    ).to(device)

    total_params = sum(p.numel() for p in model.parameters())
    print(f"Parameters: {total_params:,}")

    # ---- Data ----
    train_dataset = VanDerPolDataset(CONFIG["train_path"])
    test_dataset  = VanDerPolDataset(CONFIG["test_path"])

    train_loader = data.DataLoader(
        train_dataset,
        batch_size=CONFIG["batch_size"],
        shuffle=True,
    )
    test_loader = data.DataLoader(
        test_dataset,
        batch_size=CONFIG["batch_size"],
        shuffle=False,
    )

    print(f"Train samples: {len(train_dataset)}")
    print(f"Test  samples: {len(test_dataset)}")

    # ---- Optimizer and scheduler — Section IV ----
    optimizer = AdamW(model.parameters(), lr=CONFIG["lr"])
    scheduler = CosineAnnealingLR(optimizer, T_max=CONFIG["epochs"])

    # ---- Training ----
    best_val_loss = float("inf")

    print(f"\n{'Epoch':>6}  {'Train Loss':>12}  {'Train Impr':>12}  "
          f"{'Val Loss':>10}  {'Val Impr':>10}  {'Val Cost':>10}")
    print("-" * 70)

    history = {
        "train_loss": [], "train_impr": [],
        "val_loss":   [], "val_impr":   []
    }
    
    for epoch in range(1, CONFIG["epochs"] + 1):
        model.train()

        epoch_loss        = 0.0
        epoch_improvement = 0.0
        n_batches         = 0

        for x0, x_target, u_star in train_loader:
            x0       = x0.to(device)
            x_target = x_target.to(device)
            u_star   = u_star.to(device)

            optimizer.zero_grad()

            # Forward — return all iterations for process supervision
            all_u = model(
                x0, x_target,
                dynamics_fn=model.van_der_pol.simulate,
                return_all_iters=True,
            )

            # Loss — Eq. (15)
            loss, info = model.loss(all_u, u_star, x0, Q, R, Qf, lam=CONFIG["lam"])

            loss.backward()

            # Gradient clipping — Section IV
            # Paper calls this out specifically for stability when
            # backpropagating through the dynamics simulation
            torch.nn.utils.clip_grad_norm_(
                model.parameters(),
                max_norm=CONFIG["grad_clip"]
            )

            optimizer.step()
            
            history["train_loss"].append(train_loss)
            history["train_impr"].append(train_impr)
            history["val_loss"].append(val_loss)
            history["val_impr"].append(val_impr)

            epoch_loss        += info["loss"]
            epoch_improvement += info["improvement"]
            n_batches         += 1

        scheduler.step()

        train_loss = epoch_loss        / n_batches
        train_impr = epoch_improvement / n_batches

        # Validate every epoch
        val_loss, val_impr, val_cost = validate(model, test_loader, device, CONFIG)

        print(
            f"{epoch:>6}  "
            f"{train_loss:>12.4f}  "
            f"{train_impr:>12.4f}  "
            f"{val_loss:>10.4f}  "
            f"{val_impr:>10.4f}  "
            f"{val_cost:>10.2f}"
        )

        # Save best checkpoint
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save({
                "epoch":       epoch,
                "model_state": model.state_dict(),
                "optim_state": optimizer.state_dict(),
                "val_loss":    val_loss,
                "val_impr":    val_impr,
                "val_cost":    val_cost,
                "config":      CONFIG,
            }, CONFIG["checkpoint_path"])

    print(f"\nTraining complete. Best val loss: {best_val_loss:.4f}")
    print(f"Checkpoint saved to {CONFIG['checkpoint_path']}")


# -----------------------------------------------------------------------
# Entry point
# -----------------------------------------------------------------------

if __name__ == "__main__":
    train()